### ISSUE TITLE
Youtube Audio not filtering

### ISSUE THREAD

**Issue by KevenAyoub** [richardfrost/AdvancedProfanityFilter#251]
Hi,

The audio filtering is not working for me on youtube. The little green icon shows up and the captions are filtered but not the audio.

**Comment by richardfrost** [comment]
Sorry to hear that it isn't working for you. Sounds like you've already a few troubleshooting steps to try and track it down. Could you share a link to a video that isn't working? It might be helpful to know which browser you are using as well. Thanks for reaching out on this issue.

**Comment by KevenAyoub** [comment]
Hi Richard, I appreciate your reply. It doesn't work on any youtube video. I am using chrome.

**Comment by richardfrost** [comment]
You're welcome! I'd love to get it working for you.

There was an issue with Version 2.9.0 that was corrected in 2.9.1, but its possible it could be effecting this functionality. Usually just restart Chrome is enough to get the update. That's probably the easiest first step.

Second, I'm not sure if you have customized the configuration much, but it might be worth making a backup of your config (Options Page > Config > Export), and then restoring the defaults (same page). Once defaults have been restored, go to the Options page > Audio tab and re-enable the audio muting support, then test it on YouTube again.

A few more questions:
- Have you used it on YouTube before with success, or has it never worked?
- Have you tested any other supported sites?
- If it does work after restoring defaults (if you've customized settings much), perhaps you could share your backup so I can test it with your same situation.

**Comment by KevenAyoub** [comment]
Hi Richard, restored the settings and restarted chrome. It is still not working.

**Comment by richardfrost** [comment]
Hmmm, that is definitely strange.

Here is a [video](https://www.youtube.com/watch?v=m7Bc3pLyij0) that I just tested on. Here is the checklist of what I did after restoring the defaults:

- Temporarily added the phrase "happier" to the filter
- Enable audio muting (Options Page > Audio Tab)
- Navigate to the video linked above (or refresh the page after modifying those settings)
- Play the video
- Turn on the captions (CC button)

Hopefully that is a pretty basic test that will give us some more info on where its breaking down.

**Comment by KevenAyoub** [comment]
@richardfrost I followed those steps and now it's filtering the word happier but it won't filter the F word...

**Comment by richardfrost** [comment]
Can you link an example video? Maybe there is something wrong with the captions. Unfortunately the filter is only as good as the captions/subtitles. But if I have an example I can see if there is anything else I can do to improve it.

**Comment by KevenAyoub** [comment]
@richardfrost The only difference I see is the auto-generated captions. Here's the video:https://youtu.be/8gKzvOzya44?t=1490

**Comment by richardfrost** [comment]
Okay, found the issue. Recently YouTube added a new setting to filter curse words in their auto-generated captions. It is turned on by default everywhere, and only the channel owner (content creator) can adjust the setting. See more about the announcement [here](https://www.youtube.com/watch?v=Qg7p6qmGmjk&t=150s)

If you look at the captions the "F" word has been replaced with `[ __ ]`. I think the best way forward is to probably add that character sequence to the word list, so that it will still mute the audio when that appears. For now, can you add `[ __ ]` (open bracket space underscore underscore space close bracket) using the partial match method and see if that works? Unfortunately the other match methods don't work, because brackets are considered a word boundary in Regex. If you are using the link you sent me, it might be helpful to pause it as soon as it loads, turn on the captions, and then press play, because it can take a second or two for the captions to fully load.

I'll think about it and see if I can find a better way to implement this officially, but it very well may just be as simple as that word with a partial match method.

**Comment by KevenAyoub** [comment]
@richardfrost  That worked! Hey Richard, thanks for taking the time to work with me. The solution is pretty simple and it worked for multiple words. God bless you and take care!

**Comment by richardfrost** [comment]
You're welcome! Sorry it took so long getting to the root cause, but I'm glad we figured it out! I'll leave this open until I get something included in the filter that can work for everyone.

Thanks again for reporting this!

**Comment by KevenAyoub** [comment]
@richardfrost  It's broken again. The swear words aren't showing up in the captions anymore.

**Comment by richardfrost** [comment]
That video you linked earlier still seems to be working for me. Do you have another example that isn't working?

**Comment by KevenAyoub** [comment]
@richardfrost  The first video I sent is actually still working. This one is not: https://youtu.be/6k_O9nsG-nQ?t=2623

I think the cause is that on this video, the profanity is blocked by youtube and doesn't show up in the captions.

**Comment by richardfrost** [comment]
Unfortunately here there really isn't anything to do. The filter can only be as good as the captions/subtitles accompanying the video, and there just isn't anything to work with that I can see here. I'm not sure if this is YouTube pre-filtering by removing the words from the text (instead of replacing words with `[ __ ]`, but there just isn't anything to go off of in this case. I hope that they don't go this route for filtering, as replacing words with `[ __ ]` still gave something to mute on. Another option may be to contact the channel owner and ask them to disable the filtering option that was outlined in the video I linked [above](https://github.com/richardfrost/AdvancedProfanityFilter/issues/251#issuecomment-703759499).

On a related note, I did include a fix that won't require user intervention to filter when `[ __ ]` is detected, so once you get version 2.10.0 you should be able to remove that from your wordlist.

**Comment by richardfrost** [comment]
I'm gonna go ahead and close this because the fix for the first linked video was included in version 2.10.0, and with the second instance there is unfortunately nothing that can be done currently since the word is completely removed from the caption text. If you run into trouble related to this issue, feel free to re-open this issue.
